;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        org-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        goto-line
        org-self-insert-command
        ))
